#!/usr/bin/env ruby

require 'tempfile'
require 'fileutils'

filename = ARGV[0]

if !File.exist?(filename)
	abort("Please enter a valid MD file.")
end

puts "\n######  Generating summary for file " + filename + "  ######\n\n"

# In order to be sure to not write on existing file
timeNow = Time.now.to_f
tmpfilename = "tmp_00_" + timeNow.inspect + ".md"
temp_file = File.new(tmpfilename, "w")

summary = "\#\#Summary \n\n"
forbidden_words = ['Table of contents', 'define', 'pragma']

File.open(filename, 'r') do |f|
	f.each_line do |line|
    	if !(!line.start_with?("#") || forbidden_words.any? { |w| line =~ /#{w}/ }) 
	    	title = line.gsub("#", "").strip
		    href = "section-id-#{$.}"
		    anchor = "<div id='#{href}'/>\n\n"
		    temp_file.puts anchor + line
		    summary += "  " * (line.count("#")%4) + "- [#{title}](\##{href})" + "\n"
	 	else
	 		temp_file.puts line
	 	end   
   	end

	temp_file.close
	summary += "  \n\n"
    	system("echo \"#{summary}\" | cat - #{tmpfilename} > #{filename}")
    	system("rm #{tmpfilename}")
end



